# Site
repository: arumugamsubramanian/arumugam
favicon: images/favicon.ico

version: 2

# Personal info
name: Arumugam Subramanian
title: Senior DevOps Consultant
email: arumugamofcl@gmail.com

# Social links
twitter_username: Arumugam_S
github_username:  arumugamsubramanian
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: aarumugams
# pinterest_username:
youtube_username: "@arumugamofcl"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.png
about_content: |
  My name is Arumugam Subramanian. 
  
  ğŸ‘‹ About Me
  
  I'm a seasoned specialist with expertise in Build, Continuous Integration, and Application Lifecycle Management (ALM) tools. My passion lies in implementing agile development methodologies and automating the Environment Automation lifecycle management process.
  
  ğŸš€ Key Achievements
  
  I've designed and implemented a robust release lifecycle framework for various platforms, including mobile apps and server applications.
  
  My mission is to assist organizations in delivering valuable, high-quality software consistently and reliably by employing effective release engineering practices.
  
  ğŸ’¡ Technical Proficiency

  My technical skill set spans a wide range of areas:
  
  Scripting
  Continuous Integration tools
  Continuous Delivery Processes
  Software Configuration Management
  Build/Release Management
  Configuration Management
  
  ğŸ”§ DevOps Expertise
  
  I specialize in creating and optimizing DevOps toolchains to enable continuous releases and automate end-to-end pipelines.
  
  ğŸ› ï¸ Toolbox

  I have hands-on experience with an extensive set of tools, including:
  
  Git
  Subversion
  Jenkins
  Bamboo
  TeamCity
  Nexus Repository
  Android Studio
  XCode
  uDeploy
  Puppet
  Chef
  HP Operations Orchestration
  HP Server Automation
  HP Cloud Service Automation
  Jira Agile Software
  Apache Ivy
  Ant
  Gradle
  Crucible
  FishEye
  Sonar
  Selenium
  FitNesse
  WebSphere
  VMware
  vCenter Server
  Docker
  Kubernetes
  AWS
  Azure
  
  ğŸ“š Connect and Learn More

  I share my insights and knowledge through various platforms:

  âœï¸ Visit my blog: arumugamsubramanian.hashnode.dev
  â­ GitHub: github.com/arumugamsubramanian
  ğŸ¬ Check out my YouTube videos: youtube.com/@arumugamofcl
  Let's connect, collaborate, and explore the exciting world of DevOps and software engineering together! ğŸŒŸ

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
